//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOHIEMYTE
    {
        public int ID { get; set; }
        public int LBH_ID { get; set; }
        public string MABAOHIEM { get; set; }
        public string NOICAP { get; set; }
        public string GIATRISUDUNG { get; set; }
        public string NOIKHAM { get; set; }
        public string MAVUNG { get; set; }
        public string MANV { get; set; }
    
        public virtual LOAIBAOHIEM LOAIBAOHIEM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
