//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTKNGUOIDUNG
    {
        public int ID { get; set; }
        public Nullable<int> MATK_ND { get; set; }
        public string TENTAIKHOAN { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string NHOMTAIKHOAN { get; set; }
    
        public virtual TAIKHOANNGUOIDUNG TAIKHOANNGUOIDUNG { get; set; }
    }
}
