//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOPDONG()
        {
            this.BAOCAOs = new HashSet<BAOCAO>();
        }
    
        public string MAHD { get; set; }
        public string MANV { get; set; }
        public string LOAIHD { get; set; }
        public Nullable<System.DateTime> NGAYKIHD { get; set; }
        public Nullable<System.DateTime> NGAYHETHANHD { get; set; }
        public Nullable<double> HESOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAO> BAOCAOs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
