//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BAOCAOs = new HashSet<BAOCAO>();
            this.BAOHIEMXAHOIs = new HashSet<BAOHIEMXAHOI>();
            this.BAOHIEMYTEs = new HashSet<BAOHIEMYTE>();
            this.HOPDONGs = new HashSet<HOPDONG>();
            this.NGHIPHEPs = new HashSet<NGHIPHEP>();
            this.TAIKHOANNGUOIDUNGs = new HashSet<TAIKHOANNGUOIDUNG>();
            this.PHIEULUONGs = new HashSet<PHIEULUONG>();
        }
    
        public string MANV { get; set; }
        public string CCCD { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string NOISINH { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string MADT { get; set; }
        public string MATG { get; set; }
        public string MAQT { get; set; }
        public string MACV { get; set; }
        public string MAPB { get; set; }
        public string MATD { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAO> BAOCAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHIEMXAHOI> BAOHIEMXAHOIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHIEMYTE> BAOHIEMYTEs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual DANTOC DANTOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGHIPHEP> NGHIPHEPs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        public virtual TONGIAO TONGIAO { get; set; }
        public virtual TRINHDO TRINHDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANNGUOIDUNG> TAIKHOANNGUOIDUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEULUONG> PHIEULUONGs { get; set; }
    }
}
