//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEULUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEULUONG()
        {
            this.BAOCAOs = new HashSet<BAOCAO>();
        }
    
        public string MAL { get; set; }
        public string MANV { get; set; }
        public string MANP { get; set; }
        public string MACV { get; set; }
        public Nullable<int> HESO { get; set; }
        public Nullable<int> LUONGCOSO { get; set; }
        public Nullable<int> PHUCAP { get; set; }
        public Nullable<int> THUONG { get; set; }
        public Nullable<int> UNGLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAO> BAOCAOs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual NGHIPHEP NGHIPHEP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
