//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANNGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOANNGUOIDUNG()
        {
            this.CTTKNGUOIDUNGs = new HashSet<CTTKNGUOIDUNG>();
        }
    
        public int MATK_ND { get; set; }
        public string MANV { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string MAVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTKNGUOIDUNG> CTTKNGUOIDUNGs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
